teamName: armada-storage
teamLeadEmail: akgunjal@in.ibm.com
secretName: PROD_GLOBAL_STORAGE_CONTSTO2_IAM_APIKEY_20210407
purposeOfSecret: |
  Contoso2 Prod IAM API key used for all production environments
emailOfPersonThatGenerated: sukesh.prabhakar@in.ibm.com
